const GET_POKEDEX = 'GET_POKEDEX';
const GET_POKEDEX_DETAIL = 'GET_POKEDEX_DETAIL';
const ADD_OFFSET = 'ADD_OFFSET';
const SET_TOTAL_POKEDEX = 'SET_TOTAL_POKEDEX';
const SET_LOADING_POKEDEX = 'SET_LOADING_POKEDEX';
const SET_LOADING_POKEDEX_DETAIL = 'SET_LOADING_POKEDEX_DETAIL';

export {
  GET_POKEDEX,
  GET_POKEDEX_DETAIL,
  ADD_OFFSET,
  SET_TOTAL_POKEDEX,
  SET_LOADING_POKEDEX,
  SET_LOADING_POKEDEX_DETAIL,
};
